"""Assemble one arXiv manuscript from the authoritative paper and supplement.

The combined root is expanded so the upload contains exactly one documentclass.
Scientific text and measured tables continue to be edited in their source parts.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
PAPER = ROOT / "docs/paper"
INPUT = re.compile(r"\\(?:input|include)\{([^{}]+)\}")
BIB_START = r"\setlength{\bibsep}"
TRANSPARENCY = r"\section*{Data, supporting material, and research transparency}"
TECHNICAL_START = r"\section{Original work, semantics, and reconstruction}"


def require(condition, message):
    if not condition:
        raise ValueError(message)


def assemble():
    sources = {}

    def expand(path, stack=()):
        path = path.resolve()
        require(path.is_relative_to(PAPER), "Input is outside the paper directory")
        require(path not in stack, "Recursive TeX input")
        data = path.read_text()
        sources[str(path.relative_to(PAPER))] = hashlib.sha256(path.read_bytes()).hexdigest()

        def include(match):
            name = match.group(1)
            child = PAPER / (name if Path(name).suffix else name + ".tex")
            return ("\n% Begin source: " + name + "\n" + expand(child, (*stack, path))
                    + "\n% End source: " + name + "\n")

        return INPUT.sub(include, data)

    main = expand(PAPER / "research-report.tex")
    supplement = expand(PAPER / "technical-supplement.tex")
    preamble, body = main.split(r"\begin{document}", 1)
    require(body.count(TRANSPARENCY) == 1 and body.count(BIB_START) == 1,
            "The main paper's closing structure changed")
    scientific, closing = body.split(TRANSPARENCY)
    transparency = closing.split(BIB_START)[0].strip()
    artifact_start = "The accompanying research artifact"
    require(artifact_start in transparency, "Transparency text needs review")
    transparency = artifact_start + transparency.split(artifact_start, 1)[1]
    transparency = transparency.replace("The manuscript has not been submitted to arXiv.", "").strip()

    require(supplement.count(TECHNICAL_START) == 1 and supplement.count(BIB_START) == 1,
            "The supplement's body boundaries changed")
    technical = TECHNICAL_START + supplement.split(TECHNICAL_START, 1)[1].split(BIB_START)[0]
    require(technical.count(r"\appendix") == 1, "Expected one original appendix reset")
    technical = technical.replace(r"\appendix", "")

    require(r"\usepackage{amsmath,amssymb}" in preamble and
            r"\usepackage{booktabs,tabularx,array}" in preamble, "Main package declarations changed")
    preamble = preamble.replace(r"\usepackage{amsmath,amssymb}",
                                r"\usepackage{amsmath,amssymb,amsthm}")
    preamble = preamble.replace(r"\usepackage{booktabs,tabularx,array}",
                                r"\usepackage{booktabs,tabularx,array,longtable}")
    # Retain exactly the supplement's theorem and mathematical helper definitions.
    definitions = [line for line in supplement.split(r"\begin{document}")[0].splitlines()
                   if line.startswith((r"\newtheorem", r"\newcommand"))]
    require(len(definitions) == 4, "Review changed supplement definitions")
    preamble += "\n" + "\n".join(definitions) + "\n"

    scientific = re.sub(r"The\s+supplement gives", "The technical appendices give", scientific)
    scientific = scientific.replace("in the supplement.", "in the technical appendices.")
    scientific = scientific.replace("in the supplementary evidence.", "in the appendix evidence.")
    require(not re.search(r"\b(?:the|The)\s+(?:technical\s+)?supplement\b", scientific),
            "Review remaining standalone-supplement wording")

    # The technical section labels remain unchanged, but their section kind changes.
    appendix_labels = set(re.findall(r"\\label\{((?:sec|app):[^{}]+)\}", technical))
    def appendix_reference(match):
        return ("Appendix~" if match.group(1) in appendix_labels else "Section~") + r"\ref{" + match.group(1) + "}"
    scientific = re.sub(r"Section~\\ref\{([^{}]+)\}", appendix_reference, scientific)
    technical = re.sub(r"Section~\\ref\{([^{}]+)\}", appendix_reference, technical)

    combined = ("% Generated by scripts/prepare_combined_report.py; edit the source parts.\n"
                + preamble + r"\begin{document}" + scientific.rstrip()
                + "\n\n\\clearpage\n\\appendix\n\\section*{Technical appendices}\n"
                + technical.rstrip() + "\n\n"
                + r"\subsection{Data and research transparency}" + "\n"
                + r"\label{app:transparency}" + "\n" + transparency + "\n\n"
                + "\\clearpage\n\\setlength{\\bibsep}{1pt}\n"
                + "\\renewcommand{\\bibfont}{\\small\\raggedright}\n"
                + "\\bibliographystyle{plainnat}\n\\bibliography{references}\n\\end{document}\n")
    for token in (r"\documentclass", r"\begin{document}", r"\end{document}",
                  r"\maketitle", r"\begin{abstract}", r"\appendix", r"\bibliography{"):
        require(combined.count(token) == 1, "Combined document needs exactly one " + token)
    require(not INPUT.search(combined), "Unexpanded TeX input")
    labels = re.findall(r"\\label\{([^{}]+)\}", combined)
    require(len(labels) == len(set(labels)), "Duplicate combined labels")
    references = set(re.findall(r"\\(?:ref|eqref)\{([^{}]+)\}", combined))
    require(references <= set(labels), "Unresolved combined references")
    require(combined.count(r"\newcolumntype{Y}") == 1, "Duplicate column definition")
    destination = PAPER / "combined-report.tex"
    destination.write_text(combined)
    (PAPER / "combined-source-map.json").write_text(json.dumps({
        "generator": "scripts/prepare_combined_report.py",
        "authoritative_sources_sha256": sources,
        "combined_root_sha256": hashlib.sha256(destination.read_bytes()).hexdigest(),
        "single_document_root": True, "single_bibliography": True,
        "technical_sections_are_appendices": True,
        "transparency_moved_to_reproducibility_appendix": True,
    }, indent=2) + "\n")
    print(f"Assembled one manuscript from {len(sources)} source parts; {len(labels)} unique labels")


if __name__ == "__main__":
    assemble()
